#!/bin/bash
# =============================================================================
# Quick Commands for Phase 4 SSL Implementation
# =============================================================================
# This file contains ready-to-run commands for completing Phase 4
# =============================================================================

echo "╔═══════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                               ║"
echo "║              Phase 4 - SSL Full (strict) - Quick Commands                    ║"
echo "║                                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Step 1: Apply SSL Enhancements (REQUIRES SUDO)"
echo "=================================="
echo "sudo /home/ubuntu/Titan/apply-ssl-enhancements.sh"
echo ""
echo "OR manually:"
echo "sudo cp /etc/nginx/sites-available/zala /etc/nginx/sites-available/zala.backup.\$(date +%Y%m%d_%H%M%S)"
echo "sudo cp /home/ubuntu/Titan/nginx-zala-ssl-enhanced.conf /etc/nginx/sites-available/zala"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""

echo "📋 Step 2: Run Full SSL Tests"
echo "=================================="
echo "cd /home/ubuntu/Titan && ./scripts/test-ssl-acceptance.sh"
echo ""

echo "📋 Step 3: Verify Individual Components"
echo "=================================="
echo ""
echo "# SSL Certificate Chain"
echo "openssl s_client -connect www.zala.ir:443 -servername www.zala.ir < /dev/null 2>&1 | grep 'Verify return code'"
echo ""
echo "# HSTS Header"
echo "curl -I https://www.zala.ir 2>&1 | grep -i strict-transport-security"
echo ""
echo "# Security Headers"
echo "curl -I https://www.zala.ir 2>&1 | grep -E 'X-Frame-Options|X-Content-Type-Options|X-XSS-Protection'"
echo ""
echo "# Application Health"
echo "curl -sS https://www.zala.ir/api/health | jq '.data.status'"
echo ""

echo "📋 Step 4: Test Authentication and Real Data"
echo "=================================="
echo ""
echo "# Login and get token"
echo "TOKEN=\$(curl -sS -X POST https://www.zala.ir/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\":\"admin\",\"password\":\"admin123\"}' | jq -r '.data.token')"
echo ""
echo "# Verify authenticated endpoint returns real data"
echo "curl -sS -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  https://www.zala.ir/api/dashboard/portfolio-real | jq -r '.meta.source'"
echo "# Expected: 'real'"
echo ""

echo "📋 Step 5: Check Cloudflare SSL Mode"
echo "=================================="
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select: zala.ir domain"
echo "3. Navigate to: SSL/TLS → Overview"
echo "4. Verify: SSL/TLS encryption mode is 'Full (strict)'"
echo "5. Take screenshot for documentation"
echo ""

echo "📋 Step 6: Document Results in PR #10"
echo "=================================="
echo "1. Go to: https://github.com/raeisisep-star/Titan/pull/10"
echo "2. Add comment with:"
echo "   - Test output (all 8 tests passing)"
echo "   - Verification commands output"
echo "   - Cloudflare screenshot"
echo "   - Completion timestamp"
echo ""

echo "🔙 Rollback Commands (if needed)"
echo "=================================="
echo "LATEST_BACKUP=\$(ls -t /etc/nginx/sites-available/zala.backup.* | head -1)"
echo "sudo cp \"\$LATEST_BACKUP\" /etc/nginx/sites-available/zala"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo "curl -sS https://www.zala.ir/api/health | jq '.data.status'"
echo ""

echo "✅ All commands ready!"
echo "📖 For detailed instructions, see: /home/ubuntu/Titan/PHASE4_CURRENT_STATUS.md"
