name: Secret Scanning (Gitleaks)

# Completely disabled - manual trigger only
# Use ci-contracts.yml for automated CI testing
on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Temporarily disabled - use ci-contracts.yml workflow instead"
